### ISSUE TITLE
Ubuntu 24.04.1 LTS - basic install fail (THE RETURN)

### ISSUE THREAD

**Issue by Reverendissimo** [mentat-is/gulp#31]
After the fix to the last issue now .env and Dockerfile are there.
nevertheless
/gulp$ docker compose up -d
WARN[0000] The "EXTRA_ARGS" variable is not set. Defaulting to a blank string. 
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dgulp%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied

i don't know exactly why but looks like docker.socket service is not running. would be a good idea to put a **sudo systemctl start docker.socket** somewhere in the setup.sh

second issue:
the command docker-compose up -d must be given with supercow powers (add a sudo in the command the script gives you to start gulp.)

third issue, the .env is not loaded. need a source ./.env before issuing the docker-compose command

i strongly suggest to review line 181 of gulp sh
**echo "cd $INSTALL_DIR && docker compose up -d && gulp --reset-collab --reset-elastic gulpidx"**
 and add in the instruction the following commands.
cd ./gulp
source ./.env
sudo docker compose up -d
gulp --reset-collab --reset-elastic gulpidx

and please write somewhere that there is an option **--bind-to host port**
it's highly possible ppl don't want to install locally and maybe they want to use a remote server or a vm

**Comment by Reverendissimo** [comment]
anyway after all of the above what i get is the following:
```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://192.168.100.200:8080 (Press CTRL+C to quit)
```
but when i try to access via http
```
INFO:     192.168.100.20:39192 - "GET / HTTP/1.1" 404 Not Found
INFO:     192.168.100.20:39204 - "GET / HTTP/1.1" 404 Not Found
INFO:     192.168.100.20:39192 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

**Comment by calligraf0** [comment]
Hi thanks for troubleshooting the issue.

> i don't know exactly why but looks like docker.socket service is not running. would be a good idea to put a sudo systemctl start docker.socket somewhere in the setup.sh

I'll definitely add a check to ensure docker is running in the setup script! Thanks for the suggestion! :smile: 

> i strongly suggest to review line 181 of gulp sh
> echo "cd $INSTALL_DIR && docker compose up -d && gulp --reset-collab --reset-elastic gulpidx"
> and add in the instruction the following commands.
> cd ./gulp
> source ./.env
> sudo docker compose up -d
> gulp --reset-collab --reset-elastic gulpidx

What OS are you running on, and which version (I assume the latest on branch `develop`?). 
The command line you see should be suggested when installing a non-dev (without the --dev falg) environment and the virtualenv should be created and managed by `pipx` instead, hence why it's not needed to activate the virtual environment (unlike the dev install where the suggested command line to start gulp is: `echo "cd $INSTALL_DIR && source .venv/bin/activate && docker compose up -d && gulp --reset-collab --reset-elastic gulpidx")`.

 
> anyway after all of the above what i get is the following:
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://192.168.100.200:8080 (Press CTRL+C to quit)
> but when i try to access via http
> INFO:     192.168.100.20:39192 - "GET / HTTP/1.1" 404 Not Found
> INFO:     192.168.100.20:39204 - "GET / HTTP/1.1" 404 Not Found
> INFO:     192.168.100.20:39192 - "GET /favicon.ico HTTP/1.1" 404 Not Found

this is correct behaviour, the installation only installs the **gulp server**. To use it you need a client, either the [web ui](https://github.com/mentat-is/gulpui-web) or the [.net legecy client](https://github.com/mentat-is/gulp/releases/tag/legacy).

To ensure everything is setup properly you could try to navigate to `/docs` and a swagger page with the API should appear.

We are working to make the UI be available in the docker-compose to simplify one-shot installations, and will also ask users if they'd like to install the WebUI alongside the server in the `setup.sh` in the short future. Which I believe is what most people expect when running the setup!

> and please write somewhere that there is an option --bind-to host port

This is definitely a must as currently documentation is a little lacking regarding the command line options.
However available options are visible running gulp with the `--help` flag, like in the example below:

```bash
$ gulp --help 
usage: __main__.py [-h] [--log-to-file file path] [--log-level level]
                   [--bind-to address port] [--reset-collab]
                   [--reset-elastic indexname] [--version]

...snip...

options:
  -h, --help            show this help message and exit
  --log-to-file file path
                        also outputs log to this (rotating) file, default=stdout only.
  --log-level level     select log level, default="debug".
  --bind-to address port
                        binds to this address/port, default="localhost 8080".
  --reset-collab        reset collaboration database on start.
  --reset-elastic indexname
                        reset elasticsearch database on start (create index).
  --version             print version string and exits.
...snip...
```

**Comment by calligraf0** [comment]
Also (mostly as a reminder for myself) regarding the docker check, we should effectively also make sure current user (for which gulp and its venv are being installed for) belong to the `docker` group so they can start the compose easily (without sudo). :nerd_face:

**Comment by Reverendissimo** [comment]
Ciao Calligraf0,
installing on ubuntu server 24.04.1 LTS
as for dev or prod im installing prod for the simple reason it's the first thing in your howto
**QUICK INSTALL**
curl https://raw.githubusercontent.com/mentat-is/gulp/refs/heads/develop/setup.sh | sudo bash

**Comment by Reverendissimo** [comment]
oh remember to check both docker service and docker.socket

**Comment by calligraf0** [comment]
Installation should now be fixed and handle missing docker groups, it is now merged in `develop` . Tested on Fedora 40 and Ubuntu 24.04. 
Hope everything works more smoothly now.

If the issue persists, feel free to reopen this.

**Comment by Reverendissimo** [comment]
Great!
i'll give it a shot asap and report back if any issue occurs tnx!
